export * from "./hasElementAt";
export * from "./hasElementAtOf";
export * from "./hasProp";
export * from "./hasPropOf";
export * from "./isArray";
export * from "./isArrayOf";
export * from "./isEnum";
export * from "./isEnumOf";
export * from "./isEnumValueOf";
export * from "./isNumber";
export * from "./isObject";
export * from "./isOneOf";
// export * from './isRecordOf';
export * from "./isString";
